### ISSUE TITLE
pc_ble_driver_py.exceptions.NordicSemiException: Failed to ble_enable. Error code: NRF_ERROR_SD_RPC_SEND

### ISSUE THREAD

**Issue by hexagun** [NordicSemiconductor/pc-ble-driver-py#208]
- Using Ubuntu 20 LTS with PCA10040 and assuming connected to /dev/ttyACM0
- Compiled `pc-ble-driver` from source and connectivity files. Successfully uploaded and tested expample `HRM` application code with `sd_api_v3`. Data received on `nRF Toolbox`

- Installed dependencies with:
``` sudo apt-get install cmake swig libudev-dev python python-dev```

- Installed as:
```pip install pc-ble-driver-py```

- When attempting to run advertising.py as:
`python3 advertising.py nrf52 /dev/ttyACM0`

I get error as 

```
Serial port used: /dev/ttyACM0
Traceback (most recent call last):
  File "advertising.py", line 107, in <module>
    main(sys.argv[2])
  File "advertising.py", line 65, in main
    driver.open()
  File "/home/lab301/.local/lib/python3.8/site-packages/pc_ble_driver_py/ble_driver.py", line 106, in wrapper
    raise NordicSemiException(
pc_ble_driver_py.exceptions.NordicSemiException: Failed to open. Error code: NRF_ERROR_TIMEOUT

```
-With:
`python3 serial_port_enum.py NRF52`
```
enum_serial_ports: 1 serial ports found

Serial port #0:
|
|-  Port: "/dev/ttyACM0"
|-  Manufacturer: "SEGGER"
|-  Serial Number: "000682408096"
|-  PnP ID: ""
|-  Location ID: "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/tty/ttyACM0"
|-  Vendor ID: "1366"
|_  Product ID: "0105"
```

- `ls -la /dev/ttyACM0` gives
>crw-rw-rw-+ 1 root dialout 166, 0 Dec  7 11:43 /dev/ttyACM0

**Comment by hexagun** [comment]
Resolved by 
- Building from source
- editing `cmakelists` file to match pc-ble-driver version 4.1.1 from 4.1.4.
