### ISSUE TITLE
Failed to open. Error code: 13 when running on Raspberry Pi Zero W

### ISSUE THREAD

**Issue by xavieryin** [NordicSemiconductor/pc-ble-driver-py#57]
Trying to run on Raspberry Pi Zero W
[OS]
    latest stock RASPBIAN STRETCH LITE Version:June 2018
    setup wifi & ssh

[DK]
    PCA10028 V 1.1.0
    PCA10040 V 0.9.0

[Command Line History]
--- on PC ---
scp -pr ~/Downloads/JLink_Linux_V632h_arm/ pi@192.168.1.31:/home/pi
--- on Raspberry Pi ---
sudo cp /home/pi/JLink_Linux_V632h_arm/99-jlink.rules /etc/udev/rules.d/
sudo apt-get update
sudo apt-get dist-upgrade
mkdir /home/pi/boost
cd /home/pi/boost
wget https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.bz2
tar jxvf boost_1_65_1.tar.bz2
sudo apt install cmake swig git make gcc g++ libudev-dev python python-dev python-pip
export BOOST_ROOT=/home/pi/boost/boost_1_65_1/
cd $BOOST_ROOT
./bootstrap.sh
./b2 toolset=gcc cxxflags=-fPIC cflags=-fPIC address-model=32 link=static --with-thread --with-system --with-regex --with-date_time --with-chrono
cd /home/pi
git clone https://github.com/NordicSemiconductor/pc-ble-driver-py.git
cd pc-ble-driver-py/
git submodule init
git submodule update
cd build/
cmake -G "Unix Makefiles" ..
make
pip install wrapt
cd ../python/
cp pc_ble_driver_py/examples/advertising.py .
nano advertising.py                                                 # turn off auto flasher
python ./advertising.py NRF52 /dev/ttyACM0

[Result]
pi@raspberrypi:~/pc-ble-driver-py/python $ python ./advertising.py NRF52 /dev/ttyACM0
Serial port used: /dev/ttyACM0
Traceback (most recent call last):
  File "./advertising.py", line 79, in <module>
    main(sys.argv[2])
  File "./advertising.py", line 55, in main
    driver.open()
  File "/home/pi/pc-ble-driver-py/python/pc_ble_driver_py/ble_driver.py", line 127, in wrapper
    raise NordicSemiException('Failed to {}. Error code: {}'.format(wrapped.__name__, err_code))
pc_ble_driver_py.exceptions.NordicSemiException: Failed to open. Error code: 13

**Comment by xavieryin** [comment]
By the way w/ MacBook installed pc_ble_driver_py through pip those examples runs w/o problem

**Comment by xavieryin** [comment]
add information printed from BLEDriver.log_message_handler:

Serial port used: /dev/ttyACM0
Successfully opened /dev/ttyACM0. Baud rate: 115200. Flow control: none. Parity: none.

    1/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
State change: STATE_START -> STATE_RESET

    2/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
       1 ->  []
               type:          RESERVED_5 reliable: no seq#:0 ack#:0 payload_length:0 data_integrity:0 err_code:0
    3/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
State change: STATE_RESET -> STATE_UNINITIALIZED

    4/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
       2 ->  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
       3 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
    5/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
       4 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
    6/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
       5 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
    7/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
       6 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
    8/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
       7 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
    9/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
       8 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   10/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
       9 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   11/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      10 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   12/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      11 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   13/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      12 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   14/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      13 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   15/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      14 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   16/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      15 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   17/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      16 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   18/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      17 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   19/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      18 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   20/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      19 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   21/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      20 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   22/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      21 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   23/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      22 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   24/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      23 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   25/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      24 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   26/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      25 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   27/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      26 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   28/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      27 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   29/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      28 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   30/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      29 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   31/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      30 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   32/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      31 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
   33/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      32 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
      33 ->  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
   34/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      34 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
      35 ->  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
   35/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
      36 ->  [02 7d ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC_RESP]
      37 ->  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
State change: STATE_UNINITIALIZED -> STATE_FAILED

   36/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
   37/ 0 <-  [01 7e ]
               type: LINK_CONTROL_PACKET reliable: no seq#:0 ack#:0 payload_length:2 data_integrity:0 err_code:0
               [SYNC]
Traceback (most recent call last):
  File "/home/pi/pc-ble-driver-py/python/pc_ble_driver_py/examples/heart_rate_collector.py", line 187, in <module>
    main(serial_port)
  File "/home/pi/pc-ble-driver-py/python/pc_ble_driver_py/examples/heart_rate_collector.py", line 149, in main
    collector.open()
  File "/home/pi/pc-ble-driver-py/python/pc_ble_driver_py/examples/heart_rate_collector.py", line 67, in open
    self.adapter.driver.open()
  File "/home/pi/.local/lib/python2.7/site-packages/pc_ble_driver_py/ble_driver.py", line 127, in wrapper
    raise NordicSemiException('Failed to {}. Error code: {}'.format(wrapped.__name__, err_code))
pc_ble_driver_py.exceptions.NordicSemiException: Failed to open. Error code: 13

**Comment by olpossum** [comment]
I am having the same issue using the NRF51-DONGLE/Ubuntu 16.04 and installing pc_ble_driver_py through pip.  I also have been able to use the nrfconnect software to run serial UART application, so I know that communication with the device should be possible.

[This link](https://devzone.nordicsemi.com/f/nordic-q-a/14849/pc-ble-driver-py-driver-open-fails) references flashing /pc_ble_driver_py/hex/connectivity_115k2_with_s130_2.0.1.hex fixing the issue, however it seems that this file is no longer included with the repo.

**Comment by olpossum** [comment]
I found the referenced file [here](https://github.com/NordicSemiconductor/pc-ble-driver/tree/master/hex/sd_api_v2). If you installed the pc-ble-driver from source (it looks like you did) just grab the connectivity_115k2_with_s130_2.0.1.hex file and flash it onto your device with nrfjprog.

**Comment by xavieryin** [comment]
@olpossum 
git clone pc-ble-driver and you can find the binary in old commits.
Besides, If your "NRF51-DONGLE" is pca10000 then you may be hopeless since this an old-versioned nRF51 and does not support proper softdevice/SDK that connectivity firmwares use. You can take a look at compatibility matrix for more detail.

Anyway, I believe the problem is about the interface MCU since:
1. same DK w/ same nRF / interface MCU FW works on Mac
2. same DK w/ same nRF FW works when interface MCU is bypassed (Raspberry Pi directly communicates to nRF through UART), just by necessary changes to use serial port /dev/ttyS0 with HWFC

I gave up locating the root cause why DK cannot be used w/ Pi out of box since the direct connect setup fits better for my prototyping mission. It's fine with me that Nordic choose to close this issue if it doesn't attract too much interest.

**Comment by xavieryin** [comment]
update status:
The open problem looks like a multi-threading timing issue. Waiting for pd-ble-driver fix to be ported for SD API V3. In the mean while, by enabling Python logging module with DEBUG level and uncomment the line in log_message_handler in ble_driver.py things gets better on my site.

**Comment by bihanssen** [comment]
Closing due to inactivity, and due to the fact that pc-ble-driver-py 0.12 was released since. Consider posting on devzone if there is still an issue.
